"""add subcategories table and update product relationship

Revision ID: 6eeef6cead98
Revises: d1b3f39b0236
Create Date: 2025-07-21 14:34:34.970035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eeef6cead98'
down_revision: Union[str, Sequence[str], None] = 'd1b3f39b0236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ka', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('api_subcategory_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='_category_subcategory_uc')
    )
    op.create_index(op.f('ix_subcategories_api_subcategory_id'), 'subcategories', ['api_subcategory_id'], unique=True)
    op.drop_constraint(op.f('_parent_name_uc'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.add_column('products', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'subcategory_id')
    op.add_column('categories', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_constraint('_category_name_uc', 'categories', type_='unique')
    op.create_unique_constraint(op.f('_parent_name_uc'), 'categories', ['parent_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_subcategories_api_subcategory_id'), table_name='subcategories')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
